"""PDF output for tax report — professional statement layout."""

from __future__ import annotations

from datetime import date
from decimal import Decimal
from pathlib import Path

from fpdf import FPDF

from decaf import __version__
from decaf.models import TaxReport

_MARGIN = 15
_COL_GRAY = (240, 240, 240)
_HEADER_BLUE = (41, 65, 122)


class _TaxPDF(FPDF):
    def __init__(self, report: TaxReport) -> None:
        super().__init__(orientation="L", unit="mm", format="A4")
        self._report = report
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(_MARGIN, _MARGIN, _MARGIN)

    def header(self) -> None:
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*_HEADER_BLUE)
        self.cell(
            0, 10,
            f"Italian Tax Report - Dichiarazione dei Redditi {self._report.tax_year}",
            new_x="LMARGIN", new_y="NEXT",
        )
        self.set_font("Helvetica", "", 8)
        self.set_text_color(100, 100, 100)
        self.cell(
            0, 5,
            f"Account: {self._report.account.account_id} | "
            f"Holder: {self._report.account.holder_name} | "
            f"Broker: Interactive Brokers Ireland Limited | "
            f"Base Currency: {self._report.account.base_currency}",
            new_x="LMARGIN", new_y="NEXT",
        )
        self.line(_MARGIN, self.get_y() + 1, self.w - _MARGIN, self.get_y() + 1)
        self.ln(5)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(140, 140, 140)
        self.cell(
            0, 10,
            f"Generated by decaf v{__version__} on {date.today().isoformat()} | "
            f"Page {self.page_no()}/{{nb}}",
            align="C",
        )

    def section_title(self, title: str) -> None:
        self.ln(3)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*_HEADER_BLUE)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)

    def table(self, headers: list[str], widths: list[float], rows: list[list[str]]) -> None:
        # Header row
        self.set_font("Helvetica", "B", 7)
        self.set_fill_color(*_COL_GRAY)
        for header, w in zip(headers, widths):
            self.cell(w, 6, header, border=1, fill=True, align="C")
        self.ln()

        # Data rows
        self.set_font("Helvetica", "", 7)
        for i, row in enumerate(rows):
            if i % 2 == 1:
                self.set_fill_color(250, 250, 255)
                fill = True
            else:
                fill = False
            for val, w in zip(row, widths):
                align = "R" if _looks_numeric(val) else "L"
                self.cell(w, 5, val, border=0, fill=fill, align=align)
            self.ln()

    def summary_kv(self, items: list[tuple[str, str]]) -> None:
        self.set_font("Helvetica", "", 9)
        for label, value in items:
            self.cell(80, 6, label, new_x="END")
            self.set_font("Helvetica", "B", 9)
            self.cell(60, 6, value, new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 9)


def write_pdf(report: TaxReport, path: Path) -> None:
    """Write the tax report as a professional PDF."""
    pdf = _TaxPDF(report)
    pdf.alias_nb_pages()

    # --- Page 1: Summary ---
    pdf.add_page()
    pdf.section_title("Tax Summary")
    pdf.summary_kv([
        ("Total IVAFE (Quadro RW)", f"EUR {report.total_ivafe:,.2f}"),
        ("Net Capital Gains/Losses (Quadro RT)", f"EUR {report.net_capital_gain_loss:,.2f}"),
        ("Gross Interest Income (Quadro RL)", f"EUR {report.total_gross_interest_eur:,.2f}"),
        ("Foreign Withholding Tax (Quadro RL)", f"EUR {report.total_wht_eur:,.2f}"),
    ])

    pdf.ln(3)
    pdf.section_title("Forex Threshold Analysis (art. 67(1)(c-ter) TUIR)")
    pdf.summary_kv([
        ("Threshold", "EUR 51,645.69"),
        ("Result", "BREACHED" if report.forex_threshold_breached else "NOT BREACHED"),
        ("Max Consecutive Business Days", str(report.forex_max_consecutive_days)),
        ("First Breach Date", report.forex_first_breach_date.isoformat() if report.forex_first_breach_date else "N/A"),
    ])

    # --- Quadro RW ---
    pdf.ln(3)
    pdf.section_title("Quadro RW - Foreign Asset Monitoring + IVAFE")
    rw_headers = ["Cod.", "ISIN", "Symbol", "Description", "Country", "Initial EUR", "Final EUR", "Days", "IVAFE"]
    rw_widths = [12, 35, 18, 55, 16, 28, 28, 15, 22]
    rw_rows = [
        [
            str(l.codice_investimento), l.isin, l.symbol,
            l.description[:30], l.country,
            f"{l.initial_value_eur:,.2f}", f"{l.final_value_eur:,.2f}",
            str(l.days_held), f"{l.ivafe_due:,.2f}",
        ]
        for l in report.rw_lines
    ]
    rw_rows.append(["", "", "", "", "TOTAL", "", "", "", f"{report.total_ivafe:,.2f}"])
    pdf.table(rw_headers, rw_widths, rw_rows)

    # --- Quadro RT ---
    pdf.section_title("Quadro RT - Capital Gains/Losses")
    if report.rt_lines:
        rt_headers = ["Symbol", "ISIN", "Sell Date", "Qty", "Proceeds EUR", "Cost EUR", "Gain/Loss EUR", "Forex", "IB P/L"]
        rt_widths = [18, 35, 25, 15, 30, 30, 30, 15, 30]
        rt_rows = [
            [
                l.symbol, l.isin, l.sell_date.isoformat(),
                f"{l.quantity:,.0f}",
                f"{l.proceeds_eur:,.2f}", f"{l.cost_basis_eur:,.2f}",
                f"{l.gain_loss_eur:,.2f}",
                "Yes" if l.is_forex else "No",
                f"{l.ib_fifo_pnl:,.2f}",
            ]
            for l in report.rt_lines
        ]
        rt_rows.append(["", "", "", "", "", "NET", f"{report.net_capital_gain_loss:,.2f}", "", ""])
        pdf.table(rt_headers, rt_widths, rt_rows)
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 6, "No realized gains or losses in this tax year.", new_x="LMARGIN", new_y="NEXT")

    # --- Quadro RL ---
    pdf.section_title("Quadro RL - Investment Income")
    if report.rl_lines:
        rl_headers = ["Description", "Currency", "Gross", "Gross EUR", "WHT", "WHT EUR", "Net EUR"]
        rl_widths = [70, 18, 25, 28, 25, 28, 28]
        rl_rows = [
            [
                l.description[:40], l.currency,
                f"{l.gross_amount:,.2f}", f"{l.gross_amount_eur:,.2f}",
                f"{l.wht_amount:,.2f}", f"{l.wht_amount_eur:,.2f}",
                f"{l.net_amount_eur:,.2f}",
            ]
            for l in report.rl_lines
        ]
        total_net = report.total_gross_interest_eur - report.total_wht_eur
        rl_rows.append([
            "", "TOTALS", "",
            f"{report.total_gross_interest_eur:,.2f}", "",
            f"{report.total_wht_eur:,.2f}",
            f"{total_net:,.2f}",
        ])
        pdf.table(rl_headers, rl_widths, rl_rows)
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 6, "No investment income in this tax year.", new_x="LMARGIN", new_y="NEXT")

    path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(path))


def _looks_numeric(s: str) -> bool:
    s = s.replace(",", "").replace(" ", "").replace("EUR", "")
    try:
        float(s)
        return True
    except ValueError:
        return False
